config/routes.rb
Rails.application.routes.draw do
  get "errors/not_found"
  get "errors/internal_server_error"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "flights#index"

  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/airport.rb
class Airport < ApplicationRecord
  validates :code, length: {is: 3}

  has_many :departure_flights, foreign_key: "departure_airport_id", class_name: "Flight"
  has_many :arrival_flights, foreign_key: "arrival_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings, dependent: :destroy

  def details
    "Flight #{info}"
  end

  def info
    "from #{departure_airport.code} to #{arrival_airport.code} at #{pretty_start_time}"
  end

  def pretty_start_time
    start_time.strftime("%A, %d %b %Y %l:%M %p")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  validates_presence_of :name, :email
  validates :name, :email, length: {minimum: 3}
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP

  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight_id = params[:flight_id]
    @num_tickets = params[:num_tickets]
    @flight = Flight.find(@flight_id)
    @booking = @flight.bookings.build
    @num_tickets = params[:num_tickets].to_i
    @num_tickets.times { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.confirmation_email(passenger).deliver_later
      end
      redirect_to @booking
    else
      @flight = @booking.flight
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @depature_codes = Airport.all.map { |airport| [airport.code, airport.id] }
    @arrival_codes = @depature_codes
    @num_passengers = [1, 2, 3, 4]
    @dates = Flight.order(:start_time).to_a.map { |flight| flight.start_time.to_date }.uniq.map { |date| [date.strftime("%A, %d %b %Y"), date.strftime("%Y%m%d")] }
    if search_query_existed?
      departure_airport_id = params[:departure_code]
      arrival_airport_id = params[:arrival_code]
      start_date = Date.strptime(params[:date], "%Y%m%d")
      start_time = start_date.beginning_of_day..start_date.end_of_day
      @matched_flights = Flight.includes(:departure_airport, :arrival_airport).where(departure_airport_id:, arrival_airport_id:, start_time:).order(:start_time)
      @num_tickets = params[:num_tickets]
    end
  end

  private def search_query_existed?
    params[:departure_code] && params[:arrival_code] && params[:date] && params[:num_tickets]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="<%= controller_name %> <%= controller_name %>-<%= action_name %>">
  <div class="container page">
    <h1 class="page__title">New booking form</h2>
    <p class="info"><span class="info-type">Flight date:</span> <%= @flight.pretty_start_time %></p>
    <p class="info"><span class="info-type">Depature airport:</span> <%= @flight.departure_airport.code %></p>
    <p class="info"><span class="info-type">Arrival airport:</span> <%= @flight.arrival_airport.code %></p>
    <%= form_with model: @booking do |form| %>
      <%= form.hidden_field :flight_id %>
      <% if @booking.errors.any? %>
        <div class="errors">
          <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved</h2>
          <ul>
            <% @booking.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <p class="info-type">Passengers</p>
      <p class="info-instruct">Please enter information for each passengers</p>
      <%= content_tag :div, nil, data: { controller: "passengers", passengers_number_value: @num_tickets } do %>
        <%= content_tag :div, data: { passengers_target: "form" } do %>
          <%= form.fields_for :passengers, @booking.passengers do |passenger_form| %>
            <div class="passenger" data-passengers-target="passenger">
              <div class="field">
                <%= passenger_form.label :name %>
                <%= passenger_form.text_field :name, placeholder: "Enter your name", required: true %>
              </div>
              <div class="field">
                  <%= passenger_form.label :email %>
                  <%= passenger_form.text_field :email, placeholder: "Enter your email", required: true %>
              </div>
            </div>
          <% end %>
        <% end %>


        <%= button_tag "Add passenger", data: { action: "passengers#append" } %>

        <%= button_tag "Remove", data: { action: "passengers#remove" } %>

        <template data-passengers-target="template" >
          <div class="passenger" data-passengers-target="passenger">
            <div class="field">
                <label for="booking_passengers_attributes___count___name">Name</label>
                <input required placeholder="Enter your name" type="text" name="booking[passengers_attributes][__count__][name]" id="booking_passengers_attributes___count___name">
            </div>
            <div class="field">
                <label for="booking_passengers_attributes___count___email">Email</label>
                <input required placeholder="Enter your email" type="text" name="booking[passengers_attributes][__count__][email]" id="booking_passengers_attributes___count___email">
            </div>
          </div>
        </template>

      <% end %>
      <%= form.submit class: "button primary-btn" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Booking info</h1>
<p>Departure code: <%= @flight.departure_airport.code %></p>
<p>Arrival code: <%= @flight.arrival_airport.code %></p>
<p>Passengers</p>
<ul>
  <% @passengers.each_with_index do |passenger, index| %>
    <li>
      <p>Passenger <%= index + 1 %></p>
      <p>Name: <%= passenger.name %></p>
      <p>Email: <%= passenger.email %></p>
    </li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<div class="<%= controller_name %> <%= controller_name %>-<%= action_name %>">
  <div class="container__item logo-cont">
      <div class="logo">
        <h1 class="logo__title">Flight Booker</h1>
        <%= image_tag "plane-icon-original.svg", size: "48", alt: "Airplane icon", class: "logo__img" %>
      </div>
  </div>

  <div class="container__item flight-form-cont">
      <%= form_with url: "/flights", method: "get", class: "form flex-col-cont" do %>
        <div class="fields container__item">
          <div class="field">
            <%= label_tag :departure_code, "Departure code" %>
            <%= select_tag :departure_code, options_for_select(@depature_codes) %>
          </div>
          <div class="field">
            <%= label_tag :arrival_code, "Arrival code" %>
            <%= select_tag :arrival_code, options_for_select(@arrival_codes) %>
          </div>
          <div class="field">
            <%= label_tag :num_tickets, "Number of passengers" %>
            <%= select_tag :num_tickets, options_for_select(@num_passengers) %>
          </div>
          <div class="field">
            <%= label_tag :date, "Date" %>
            <%= select_tag :date, options_for_select(@dates) %>
          </div>
        </div>
        <div class="container__item submit-cont"><%= submit_tag "Search", class: "button" %></div>
      <% end %>
  </div>


  <% if @matched_flights&.any? %>
    <div class="container__item flights-select-cont">
      <div class="flights-select">
        <h2 class="flights-select__title">Select your flight</h2>
        <%= form_with url: new_booking_path, method: "get", class: "flights-select__form select-form" do |form| %>
          <%= form.collection_radio_buttons(:flight_id, @matched_flights, :id, :details) do |b| %>
            <div class="flights-select__item">
              <%= b.label { b.radio_button + b.text } %>
            </div>
          <% end %>
          <%= hidden_field_tag "num_tickets", params[:num_tickets] %>
          <%= form.submit "Submit", class: "select-form__submmit button" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>